name: Pull Request Event

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-client-pr:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run client_pull_request script
      run: python client.py ${{ secrets.SERVER_IP }} ${{ secrets.SERVER_PORT }} "pull request action"
