name: Pull Request Event

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-client-pr:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: run test
      run: echo "999"
      # run: echo "SERVER_TEST="

    - name: Print environment variables
      env:
          SERVER_TEST: ${{ secrets.TEST_KEY }}
      run: echo "SERVER_TEST=$TEST_KEY"
    
    - name: chmod
      run: sudo chmod 777 sleep.sh

    - name: sleep
      run: ./sleep.sh

    - name: test key
      run: echo "999"
    
    - name: Run client_pull_request script
      run: python3 client.py "${{ secrets.SERVER_IP }}" ${{ secrets.SERVER_PORT }} "pull action" ${{ secrets.TEST_KEY }}

    
